name: my_project
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - autoflake=1.4
  - black=19.10b0
  - m2r2=0.3.1
  - mypy=0.790
  - nox=2021.6.12
  - pip=20.2.4
  - pre-commit=2.14.0
  - pytest=6.1.1
  - pytest-cov=2.10.1
  - python=^3.8
  - sphinx=3.2.1
  - sphinx-autodoc-typehints=1.12.0
  - sphinx_rtd_theme=0.4.3
